// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KHEC6CiVc2lBK6DHnM1n8qM3mRRAwD8',
    appId: '1:570490863112:android:5fc6a220a5edbd306b9bbd',
    messagingSenderId: '570490863112',
    projectId: 'todo-app-4ad37',
    databaseURL: 'https://todo-app-4ad37-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-4ad37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsZhxVboCaWKn7PkZGu5BPj8ysosmkSsQ',
    appId: '1:570490863112:ios:1af03e21361635726b9bbd',
    messagingSenderId: '570490863112',
    projectId: 'todo-app-4ad37',
    databaseURL: 'https://todo-app-4ad37-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-4ad37.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
